### ISSUE TITLE
Unable to install package via composer without adding path manually

### ISSUE THREAD

**Issue by Sebobo** [networkteam/Netwokteam.Neos.SentryClient#3]
Can you make this package available on packagist?

Thx,
Sebastian

**Comment by drlimbo** [comment]
to have the package on packagist would be awesome!

**Comment by networkteamcom** [comment]
Is now available on packagist.
https://packagist.org/packages/networkteam/neos-sentryclient

**Comment by drlimbo** [comment]
THANKS @networkteamcom - this was fast ⚡
