### ISSUE TITLE
User Details (User / Browser) missing on Sentry

### ISSUE THREAD

**Issue by drlimbo** [networkteam/Netwokteam.Neos.SentryClient#4]
### Description
Netwokteam.Neos.SentryClient **does not send User Details (User / Browser) to Sentry**. 

### Steps to Reproduce
1. Install Netwokteam.Neos.SentryClient
2. Configuration (add dsn)
3. Produce an Error 💥
4. Check Error on Sentry

#### Expected behavior
Error will be logged to Sentry including User Details (User / Browser)

#### Actual behavior
Error will be logged to Sentry **without** User Details (User / Browser)

![screenshot 2018-11-08 at 15 05 31](https://user-images.githubusercontent.com/1118783/48203448-d2a58680-e367-11e8-929c-2397c4821a41.png)

### Affected Versions
Neos: 4.1.7
networkteam/neos-sentryclient: v4.0.1

**Comment by ger4003** [comment]
The issue is realated to https://github.com/getsentry/sentry/issues/8555

**Comment by ger4003** [comment]
Browser and plattform information was added with 5.0.2 of https://github.com/networkteam/Networkteam.SentryClient

To get the new version run `composer update networkteam/sentryclient` in your project root directory.
