### ISSUE TITLE
Upgrading "networkteam/sentryclient" to use Sentry SDK V2

### ISSUE THREAD

**Issue by paavo** [networkteam/Netwokteam.Neos.SentryClient#6]
Are there any plans to upgrade the dependency of "networkteam/sentryclient" from 5 to 6 to use the new Sentry SDK 2?

**Comment by drlimbo** [comment]
@christophlehmann any plans to Update networkteam/Netwokteam.Neos.SentryClient?

**Comment by christophlehmann** [comment]
Sure! PR's and especially their testing are very welcome :-)

**Comment by christophlehmann** [comment]
Next release should support Neos 5.0 too, because it's out for quite some days
